spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

env.data.secretkey =${ENV_DATA_SECRETKEY}

# Set the logging level
logging.level.root=WARN
logging.level.com.group2.theminimart=INFO
# add the following properties to enable swagger.(4 lines)
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.api-docs.path=/api/api-docs
springdoc.show-actuator=true